General:
  GamesMuteFile: 'SquelchGames.yml'
  Messages:
    Badge: "&3&l[&2BungeeTalk&3&l]&r"
    JoinMessages:
      - '%playerName% has joined with uuid %uuid% using version %version%'
      - '%playerName% has graced us with their presence.'
    LeaveMessages:
      - '&c%playerName%&t has connected to the outernet.'
      - '&c%plsyerNsmr%&r&e has left the cult.'
    ServerTransferMessages:
      - '&c&l%playerName% &a-&e&l %fromServer% >> %toServer%'
    Commands:
      Squelch:
        PlayerNotFound: 'Player %target% is not online'
        IncorrectArgsLength: 'This command requires a single PlayerName argument.'
        BlockedMessage: '&cBlocked incoming message from %sender%'
      Wins:
        Success:
          DisplayWinsOwn: 'You have a total of %wins% in this game mode %withTime% %time%!'
          DisplayWinsOther: '%other% has won %wins% times %withTime% %time%'
          DisplayFastestOwn: 'Your fastest time was: %time%'
          DisplayFastestOther: '%other%''s fastest completion time was: %time$'
          DisplayTopWinsTitle: 'Top 10 by total wins'
          DisplayTopWinsHeaders: '[Rank] - [Player]     - [Total Wins] -    [Best Time]'
          DisplayTopWinsFormat: '%position% - %other% - Total Wins: %wins% - Best Time: %time%'
          DisplayTopSpeed: 'Top 10 by speed'
          DisplayTopSoeedHeaders: '[Rank] - [Player]     - [Best Time] -    [Total Wins]'
          DisplayTopSpeedFormat: '$position% - %other% - Best Time: %time% - Total Wins: %wins%'
          WithTime: 'with a fastest time of'
        Errors:
          NotPlayer: 'This command requires additional arguments to use from console.'
          NoManager: 'Unable to determine game manager for Game mode:'
          MissingConfig: 'Unable to find config for Game mode:'
          NoLeaderboard: 'Unable to locate LeaderBoard for Game mode:'
          UnknownGameMode: 'Unknown Game Mode:'
          ReadError: 'Unable to obtain LeaderBoard values'
          IncorrectUsage: 'Unable to determine what values you were looking for.'
Games:
  Unscramble:
    Filename: 'unscramble.yml'
    LeaderBoardFile: 'unscrambleLeaderBoard.yml'
    Messages:
      Badge: '&3&l[&2Shake Scramble&3&l]&r'
      Winner: '%winner% has won, with a time of %value%'
      NoWinner: 'Nobody typed the phrase %answer% fast enough.'
      GameStart: 'is starting, first to unscramble &c%word%&r wins!! You have %gameLength% seconds!'
    Settings:
      Enabled: true
      GameLength: 30
      Frequency: 900
      StartOffset: 600
      MinimumPlayers: 2
    Rewards:
      - 'BCCommand:say Proxy says nice'
      - 'SPCommand:pay %player% 1'
  SpeedTypist:
    Filename: 'speedTypist.yml'
    LeaderBoardFile: 'speedTypistLeaderBoard.yml'
    Messages:
      Badge: '&3&l[&2Treebo Typist&3&l]&r'
      Winner: '%winner% has won, with a time of %value%'
      NoWinner: 'Nobody typed the phrase %answer% fast enough.'
      GameStart: 'is starting, first to type &c%word%&r wins!! You have %gameLength% seconds!'
    Settings:
      Enabled: true
      GameLength: 30
      Frequency: 900
      StartOffset: 300
      MinimumPlayers: 2
    Rewards:
      - 'BCCommand:say Proxy says nice'
      - 'SPCommand:pay %player% 1'
Announcer:
  Settings:
    Enabled: true
    Frequency: 900
    StartOffset: 0
    StringsFilename: 'announcer.yml'
    MuteFile: 'SquelchAnnouncer.yml'
ReservedWords:
  - '%winner%'
  - '%value%'
  - '%answer%'
  - '%word%'
  - '%gameLength%'